on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4.1.3
        with: #Action Inputs start here https://github.com/marketplace/actions/release-please-action#advanced-release-configuration
          token: ${{ secrets.RELEASE_PLEASE_REPO }}
          release-type: terraform-module # Could be changed to terraform-module? Check requirements https://github.com/marketplace/actions/release-please-action#release-types-supported
  module-review:
    name: Individual module review
    runs-on: ubuntu-latest
    needs: find-changes
    strategy:
      matrix: 
        module: ${{ fromJson(needs.find-changes.outputs.changed-modules) }}
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: terraform init
      - run: terraform fmt -diff -check
      - run: terraform validate
