name: Make API Request to Terraform Cloud to reconcile module version with GitHub release

on:
  release:
    types: [released]

jobs:
  make-api-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release version
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.RELEASE_PLEASE_REPO_NEW }}
          view_top: 1

      - name: Make API Request
        id: api_request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://app.terraform.io/api/v2/organizations/PersonalUseHL/registry-modules/private/PersonalUseHL/beta-feature/h2/versions'
          method: 'POST'
          bearerToken: ${{ secrets.API_HEADERS }}
          customHeaders: '{"Content-Type": "application/vnd.api+json"}'
          data: '{ "data": {"type": "registry-module-versions", "attributes": { "version": "${{ steps.last_release.outputs.tag_name }}", "commit-sha": "${{ github.sha }}" } } }'

      - name: Show API Response Status
        run: |
          echo "Response Status: ${{ steps.api_request.outputs.status }}"

      - name: Show API Response Data
        run: |
          echo "Response Data: ${{ steps.api_request.outputs.data }}"
