name: Make API Request to Terraform Cloud to reconcile module version with GitHub release

on:
  release:
    types: [released]

jobs:
  make-api-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make API Request
        run: | 
          curl -H 'Authorization: Bearer ${{ secrets.API_HEADERS }}' -H 'Content-Type: application/vnd.api+json' --d '{ "data": {"type": "registry-module-versions", "attributes": { "version": "${{ github.event.release.tag_name }}", "commit-sha": "${{ github.sha }}" } } }' -X POST https://app.terraform.io/api/v2/organizations/PersonalUseHL/registry-modules/private/PersonalUseHL/beta-feature/h2/versions
